### PR TITLE
Change: Improved infra06.png Monorail and Maglev roof sprites

### LINKED ISSUE #44: Open GFX Base Maglev Roofs
The Open GFX Maglev station roofs do not quite match the Rail and Monorail roofs in terms of level of detail or pixel art style - generally they could just use a bit more love.  I've tried to make the curved spaceframe portion more substantial by giving it some chord depth with a lower layer, and split the coloring to be silver on top and CC below.  I've also added a CC stripe to the rather plain black columns.  I added a bit more depth to the CC clerestory on the Monorail roof while I was at it.

Best,
Station Roof 20200518

### PR DESCRIPTION
**Pull request by supermop**
This is my first PR and I am not really sure if I did this correctly, but this adds the infra06.png that has my changed roof sprites as discussed in #44 

I am also working on some tweaks to the Rail roof, but that seemed less relevant to the issue and might be more controversial, so I did not add it here.

Thanks!

Closes #44

### CODE REVIEW

**Comment by supermop** [comment]
Before:
Before Infra06

After:
After Infra06

**Comment by Andrew350** [comment]
2 things:

- I notice the transparency sprites (the yellow bits) no longer match up with the added superstructure. I don't know if that has any noticeable effect in-game (I haven't compiled to check), but may be worth looking at.

 - Given the complete fustercluck that is the OpenGFX repo, it may be worth splitting these new graphics into their own .png file. This would help distinguish them as new, _actually used_ graphics, rather than the old/unused/duplicate/triplicate/etc graphics that otherwise litter the spritesheets. Just a suggestion though, they look great either way 🙂

**Comment by supermop** [comment]
> 2 things:
> 
> * I notice the transparency sprites (the yellow bits) no longer match up with the added superstructure. I don't know if that has any noticeable effect in-game (I haven't compiled to check), but may be worth looking at.
> * Given the complete fustercluck that is the OpenGFX repo, it may be worth splitting these new graphics into their own .png file. This would help distinguish them as new, _actually used_ graphics, rather than the old/unused/duplicate/triplicate/etc graphics that otherwise litter the spritesheets. Just a suggestion though, they look great either way 🙂

Don't line up with the CC frame, or with the silver part? I didn't change those sprites at all, so presumably they'd be the same as last year, but not sure. I don't have access to photoshop for a few days, so I'm not able to modify the PNG at the moment. 

I am neutral on providing the sprites as a standalone png vs revising the big infra06 ... either way is fine with me, I just assumed replacing the big sheet would be easier as no code would need to change.

**Comment by supermop** [comment]
Just following up on this - is the current method of replacing infra06 unacceptable, or simply not preferred?

**Comment by LordAro** [comment]
Oops, sorry, looks like I broke it when trying to fix the commit messages. Can you remake the PR? (Use a branch other than 'master', it's bad practice and causes weirdnesses like this)

I don't think anything you did was unacceptable, but I'm no NewGRF developer either :)

**Pull request closed without merging**
