### PR TITLE
Change: Use a white cursor for better visibility

### PR DESCRIPTION
**Pull request by Andrew350**
Orange is a terrible color for the cursor. I often lose track of it against the background, especially when it flickers while moving, so I made it white to increase visibility.

### CODE REVIEW

**Comment by andythenorth** [comment]
Massive +1, I was using the WASM previews of OpenTTD.  I never normally use OpenGFX.  The OGFX cursor is horribly hard to see.

I don't think this is a valid case of "we just like what we are familiar with" either 😸

**Comment by frosch123** [comment]
The cursor is used in all climated.
Try a white cursor in arctic climate above snowline.

Orange was picked, because it is best visible in most situations.

**Comment by frosch123** [comment]
Sorry, this is a PR. I thought it was an issue.
I'll leave it for discussion then.

**Comment by andythenorth** [comment]
Many successful cursors use high contrast almost-monochrome colours
 e.g. black border on white cursor, or white border on black cursor

Original baseset cursor has no snowline visibility problem because 
1. it's fricking huge and chunky
2. it's mostly grey, and uses substantial dark shadow under lower side of sprite

**Comment by Andrew350** [comment]
> Try a white cursor in arctic climate above snowline.

I did, and made a little comparison. Top is current, middle is what's in the PR now, bottom is a test with some extra black for contrast:

cursor_arctic

My opinions:

 - Orange is definitely visible over snow, but not great everywhere else.

 - White only seems slightly less visible over snow (in-game at least), but is much more visible everywhere else.

 - White with a bit more black outline solves both issues, with the slight negative of making the cursor a bit more chonky (and perhaps a bit more work to fit into existing sprites)

Whether others agree or not is obviously important for the PR, but I will definitely be using this for my personal setup. Would love to see other input though 🙂

**Comment by TrueBrain** [comment]
So used to the iconic orange, I would hate to lose that honestly :(

Wouldn't it be a good idea to make a tiny GRF like "white-mouse.grf" that does this? That allows others to use it too, without people who are very much used to the orange losing that? :D

**Comment by Andrew350** [comment]
That is definitely an option, if the consensus is against the change 🙂

**Comment by LordAro** [comment]
Executive decision: Reject this change. Less visible on snow (even with the bold outline, which is an improvement), and less reason to do so now that the flickering mouse issues have been fixed

Thanks for giving it a go!

**Pull request closed without merging**
